spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_app
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      data-platform: org.hibernate.dialect.PostgreSQLDialect

